name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org/

    - run: npm ci
    - run: npm run compile
    - run: npm test
      env:
        CI: true

    - run: npm ci
    - run: npm run compile
    - run: npm publish --provenance --access public
      env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
